name: mpirical-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mpich
  - mpi4py
  - pytest
  - pytest-cov
  - coverage
  - codecov
  - dill
  - cloudpickle
  - tblib
  - versioneer
  - pyyaml
  - six
