version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-3.6-mpich
      - test-2.7-mpich
      - test-2.7-openmpi
      - test-docs
      - test-linting

default-job: &default-job
  docker:
    - image: continuumio/miniconda:latest
  steps:
    - checkout
    - restore_cache:
        key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
    - run:
        name: Install conda environment
        command: .circleci/install.sh
    - run:
        name: Running checks
        command: |
          source activate ${ENV_NAME}
          .circleci/${CHECK_SCRIPT}
    - save_cache:
        key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - "/opt/conda/envs/${ENV_NAME}/"
          - "/opt/conda/pkgs"

jobs:

  test-3.6-mpich:
    <<: *default-job
    environment:
      ENV_NAME: "mpirical"
      ENV_SCRIPT: "env-3.6-mpich.yml"
      CHECK_SCRIPT: "test-unit-coverage.sh"

  test-2.7-mpich:
    <<: *default-job
    environment:
      ENV_NAME: "mpirical"
      ENV_SCRIPT: "env-2.7-mpich.yml"
      CHECK_SCRIPT: "test-unit-only.sh"

  test-2.7-openmpi:
    <<: *default-job
    environment:
      ENV_NAME: "mpirical"
      ENV_SCRIPT: "env-2.7-openmpi.yml"
      CHECK_SCRIPT: "test-unit-only.sh"
      MPIRICAL_MPIRUN: "mpirun --allow-run-as-root"
      OMPI_MCA_rmaps_base_oversubscribe: "1"

  test-docs:
    <<: *default-job
    environment:
      ENV_NAME: "mpirical"
      ENV_SCRIPT: "env-3.6-mpich.yml"
      CHECK_SCRIPT: "test-docs.sh"

  test-linting:
    <<: *default-job
    environment:
      ENV_NAME: "mpirical"
      ENV_SCRIPT: "env-3.6-mpich.yml"
      CHECK_SCRIPT: "test-linting.sh"
