version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - test-2.7

jobs:
  test-3.7:
    docker:
      - image: frolvlad/alpine-miniconda3

    steps:
      - run: apk add --no-cache build-base ca-certificates git openssh
      - checkout
      - restore_cache:
          keys:
            - conda-pkgs
      - run: conda create -q -n mpi-pytest-dev python=3.7 && conda env update -f environment-dev.yml
      - run: source activate mpi-pytest-dev && pip install --no-deps -e .
      - save_cache:
          key: conda-pkgs
          paths:
            - /opt/conda/pkgs
      - run:
          name: Running Unit Tests
          command: |
            source activate mpi-pytest-dev
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml tests

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

  test-3.6:
    docker:
      - image: frolvlad/alpine-miniconda3

    steps:
      - run: apk add --no-cache build-base ca-certificates git openssh
      - checkout
      - restore_cache:
          keys:
            - conda-pkgs
      - run: conda create -q -n mpi-pytest-dev python=3.6 && conda env update -f environment-dev.yml
      - run: source activate mpi-pytest-dev && pip install --no-deps -e .
      - save_cache:
          key: conda-pkgs
          paths:
            - /opt/conda/pkgs
      - run:
          name: Running Unit Tests
          command: |
            source activate mpi-pytest-dev
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml tests

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

  test-3.5:
    docker:
      - image: frolvlad/alpine-miniconda3

    steps:
      - run: apk add --no-cache build-base ca-certificates git openssh
      - checkout
      - restore_cache:
          keys:
            - conda-pkgs
      - run: conda create -q -n mpi-pytest-dev python=3.5 && conda env update -f environment-dev.yml
      - run: source activate mpi-pytest-dev && pip install --no-deps -e .
      - save_cache:
          key: conda-pkgs
          paths:
            - /opt/conda/pkgs
      - run:
          name: Running Unit Tests
          command: |
            source activate mpi-pytest-dev
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml tests

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

  test-2.7:
    docker:
      - image: frolvlad/alpine-miniconda3

    steps:
      - run: apk add --no-cache build-base ca-certificates git openssh
      - checkout
      - restore_cache:
          keys:
            - conda-pkgs
      - run: conda create -q -n mpi-pytest-dev python=2.7 && conda env update -f environment-dev.yml
      - run: source activate mpi-pytest-dev && pip install --no-deps -e .
      - save_cache:
          key: conda-pkgs
          paths:
            - /opt/conda/pkgs
      - run:
          name: Running Unit Tests
          command: |
            source activate mpi-pytest-dev
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml tests

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
