version: 2

workflows:
  version: 2
  default:
    jobs:
      - check-3.6
      - check-2.7
      - check-docs
      - check-linting

jobs:

  check-3.6:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      PYTHON: "3.6"
      ENV_NAME: "mpirical-ci"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-3.6-{{ checksum "environment-dev.yml" }}
      - run:
          name: Install and activate conda environment
          command: .circleci/install.sh
      - run:
          name: Running tests with coverage
          command: |
            source activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml --cov=./ mpirical/tests/
      - save_cache:
          key: deps-{{ .Branch }}-3.6-{{ checksum "environment-dev.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"
      - run:
          name: Report code coverage
          command: |
            source activate ${ENV_NAME}
            echo "[Uploading Coverage]"
            codecov

  check-2.7:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      PYTHON: "2.7"
      ENV_NAME: "mpirical-ci"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "environment-dev.yml" }}
      - run:
          name: Install and activate conda environment
          command: .circleci/install.sh
      - run:
          name: Running tests with coverage
          command: |
            source activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml mpirical/tests/
      - save_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "environment-dev.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"

  check-docs:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      PYTHON: "3.6"
      ENV_NAME: "mpirical-ci"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "environment-dev.yml" }}
      - run:
          name: Install and activate conda environment
          command: .circleci/install.sh
      - run:
          name: Building docs
          command: |
            source activate ${ENV_NAME}
            cd docs
            make html
      - save_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "environment-dev.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"
      - store_artifacts:
          path: docs/_build/html
          destination: html

  check-linting:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      PYTHON: "3.6"
      ENV_NAME: "mpirical-ci"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "environment-dev.yml" }}
      - run:
          name: Install and activate conda environment
          command: .circleci/install.sh
      - run:
          name: Check code formatting
          command: |
            source activate ${ENV_NAME}
            flake8
      - save_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "environment-dev.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"
