version: 2
jobs:
  build:
    docker:
      - image: frolvlad/alpine-miniconda3

    steps:
      - run: apk add --no-cache build-base ca-certificates git openssh
      - checkout
      - restore_cache:
          keys:
            - conda-pkgs
      - run: conda create -q -n mpi-pytest python=3.6 && conda env update -f environment-dev.yml
      - run: source activate mpi-pytest && pip install --no-deps -e .
      - save_cache:
          key: conda-pkgs
          paths:
            - /opt/conda/pkgs
      - run:
          name: Running Unit Tests
          command: source activate mpi-pytest && pytest tests
      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  default:
    jobs:
      - build
