version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-3.6
      - test-2.7

jobs:

  test-3.6:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      PYTHON: "3.6"
      ENV_NAME: "decormpi-dev"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-3.6-{{ checksum "environment-dev.yml" }}
      - run:
          name: Install and activate conda environment
          command: ./ci/install-circle.sh
      - run:
          name: Running tests
          command: |
            source activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml --cov=./ decormpi/tests/
      - save_cache:
          key: deps-{{ .Branch }}-3.6-{{ checksum "environment-dev.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"
      - run:
          name: Report Code Coverage
          command: |
            source activate ${ENV_NAME}
            echo "[Uploading Coverage]"
            codecov

  test-2.7:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      PYTHON: "2.7"
      ENV_NAME: "decormpi-dev"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "environment-dev.yml" }}
      - run:
          name: Install and activate conda environment
          command: ./ci/install-circle.sh
      - run:
          name: Running tests
          command: |
            source activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml --cov=./ decormpi/tests/
      - save_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "environment-dev.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"
