version: 2

workflows:
  version: 2
  default:
    jobs:
      - check-3.6-mpich
      - check-2.7-mpich
      - check-2.7-openmpi
      - check-docs
      - check-linting

default-job: &default-job
    docker:
      - image: continuumio/miniconda:latest
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Install conda environment
          command: .circleci/install.sh
      - run:
          name: Running checks
          command: |
            source activate ${ENV_NAME}
            .circleci/${CHECK_SCRIPT}
      - save_cache:
          key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"

jobs:

  check-3.6-mpich:
    <<: *default-job
    environment:
      ENV_NAME: "mpirical"
      ENV_SCRIPT: "env-3.6-mpich.yml"
      CHECK_SCRIPT: "check-3.6.sh"

  check-2.7-mpich:
    <<: *default-job
    environment:
      ENV_NAME: "mpirical"
      ENV_SCRIPT: "env-2.7-mpich.yml"
      CHECK_SCRIPT: "check-2.7.sh"

  check-2.7-openmpi:
    <<: *default-job
    environment:
      ENV_NAME: "mpirical"
      ENV_SCRIPT: "env-2.7-openmpi.yml"
      CHECK_SCRIPT: "check-2.7.sh"

  check-docs:
    <<: *default-job
    environment:
      ENV_NAME: "mpirical"
      ENV_SCRIPT: "env-3.6-mpich.yml"
      CHECK_SCRIPT: "check-docs.sh"

  check-linting:
    <<: *default-job
    environment:
      ENV_NAME: "mpirical"
      ENV_SCRIPT: "env-3.6-mpich.yml"
      CHECK_SCRIPT: "check-linting.sh"
