# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    - docker:
      - image: circleci/python:3.6.1

    - working_directory: ~/repo

    - steps:
      - run: apk add --no-cache build-base ca-certificates git openssh
      - checkout
      - restore_cache:
          keys:
            - conda-pkgs
      - run: conda create -q -n mpi-pytest python=3.6 && conda env update -f environment.yml
      - run: source activate mpi-pytest && pip install --no-deps -e .
      - save_cache:
          key: conda-pkgs
          paths:
            - /opt/conda/pkgs
      - run:
          name: Running Unit Tests
          command: source activate mpi-pytest && pytest tests
      - store_artifacts:
          path: test-reports
          destination: test-reports
